on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        id: release
        uses: lumynou5/github-release-action@v1
        with:
          token: ${{github.token}}
          major-tag-template: ''
          minor-tag-template: ''

      - name: Build
        run: |
          make

      - name: Upload assets
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Content-Type: application/zip" \
            -H "Content-Length: $(wc -c <dist/live-time-copier.zip)" \
            -T dist/live-time-copier.zip \
            "${UPLOAD_URL%{*}?name=live-time-copier.zip"
        env:
          GITHUB_TOKEN: ${{github.token}}
          UPLOAD_URL: ${{steps.release.outputs.upload-url}}

      - name: Upload to CWS
        uses: browser-actions/release-chrome-extension@v0.2.1
        with:
          extension-path: dist/live-time-copier.zip
          extension-id: gmamkocjpjlmbmonbbddgddhkclbchei
          oauth-client-id: ${{secrets.OAUTH_CLIENT_ID}}
          oauth-client-secret: ${{secrets.OAUTH_CLIENT_SECRET}}
          oauth-refresh-token: ${{secrets.OAUTH_REFRESH_TOKEN}}

      - name: Upload to AMO
        uses: browser-actions/release-firefox-addon@v0.2.1
        with:
          addon-path: dist/live-time-copier.zip
          addon-id: F11091D0-F375-4943-B5BE-0E65A5416E16
          release-note: ${{steps.release.outputs.change}}
          auth-api-issuer: ${{secrets.FIREFOX_API_ISSUER}}
          auth-api-secret: ${{secrets.FIREFOX_API_SECRET}}
